/**
 * Generated by PluginGenerator from webgme on Wed Nov 19 2014 17:26:52 GMT-0600 (Central Standard Time).
 */

define( [], function () {
    'use strict';
    return {
        'ACMFolder': '/1008889918/398267330',
        'ADMEditorModelingLanguage': '/1008889918',
        'ADMFolder': '/1008889918/755698918',
        'ATMFolder': '/1008889918/794302266',
        'AVMComponentModel': '/1008889918/1998840078',
        'AVMTestBenchModel': '/1008889918/1624079113',
        'AssemblyRoot': '/1008889918/1502717053',
        'Connector': '/1008889918/1045980796',
        'ConnectorComposition': '/1008889918/488584186',
        'Container': '/1008889918/1993805430',
        'CustomFormula': '/1008889918/1299690106',
        'DesertConfiguration': '/1008889918/1949671222',
        'DesertConfigurationSet': '/1008889918/206008088',
        'DomainModel': '/1008889918/481954284',
        'DomainPort': '/1008889918/126974487',
        'ExactLayoutConstraint': '/1008889918/749469140',
        'FCO': '/1',
        'Formula': '/1008889918/803021327',
        'LayoutConstraint': '/1008889918/236224320',
        'Metric': '/1008889918/1328879441',
        'PortMap': '/1008889918/1474284259',
        'Property': '/1008889918/34094492',
        'RangeLayoutConstraint': '/1008889918/1669293789',
        'RelativeLayoutConstraint': '/1008889918/24011457',
        'Requirement': '/1008889918/1220837843',
        'RequirementBase': '/1008889918/1010911100',
        'RequirementCategory': '/1008889918/1598195376',
        'RequirementsFolder': '/1008889918/1675023230',
        'Result': '/1008889918/1368062975',
        'Settings': '/1008889918/319211427',
        'SimpleFormula': '/1008889918/711037118',
        'Task': '/1008889918/91705197',
        'Test': '/1008889918/1922772359',
        'ValueFlowComposition': '/1008889918/756182296',
        'WorkSpace': '/1008889918/1826321976',
        'Workflow': '/1008889918/891929219',
    };
} );