/* global define,require */
/**
* Generated by MockModelGenerator from webgme on Tue Nov 04 2014 15:25:05 GMT-0600 (Central Standard Time).
*/
define(['mocks/CoreMock', './META'], function (CoreMock, createMeta) {
    'use strict';
    return function () {
        var core = new CoreMock(0),
            META = createMeta(core),
            options;

        options = {
            base: META.ACMFolder,
            parent: core._rootNode,
            attr: {
                'name': 'ACMFolder',
                'INFO': 'Container of components.',
                'ReadMe': '',
            }
        };
        var ID__b1efd23d_c5b9_74b7_3178_2703aaeed10e = core.createNode(options);


// ---------------------- Bases for nodes with non-meta bases -------------------------

// ---------------------- Pointers (e.g. connections) ---------------------------------
        return {
            core: core,
            META: META,
            activeNode: ID__b1efd23d_c5b9_74b7_3178_2703aaeed10e
        };
    };
});