/**
* Generated by PluginGenerator from webgme on Tue Apr 14 2015 09:56:25 GMT-0500 (Central Daylight Time).
*/

define([], function () {
    'use strict';
    return {
        'ACMFolder': '/759732751/398267330',
        'ADMEditorModelingLanguage': '/759732751',
        'ADMFolder': '/759732751/755698918',
        'ATMFolder': '/759732751/794302266',
        'AVMComponentModel': '/759732751/1998840078',
        'AVMTestBenchModel': '/759732751/1624079113',
        'AssemblyRoot': '/759732751/1502717053',
        'Connector': '/759732751/1045980796',
        'ConnectorComposition': '/759732751/488584186',
        'Container': '/759732751/1993805430',
        'CustomFormula': '/759732751/1299690106',
        'DesertConfiguration': '/759732751/1949671222',
        'DesertConfigurationSet': '/759732751/206008088',
        'DomainModel': '/759732751/481954284',
        'DomainPort': '/759732751/126974487',
        'ExactLayoutConstraint': '/759732751/749469140',
        'FCO': '/1',
        'Formula': '/759732751/803021327',
        'GlobalLayoutConstraintException': '/759732751/1226873745',
        'LayoutConstraint': '/759732751/236224320',
        'Metric': '/759732751/1328879441',
        'PortMap': '/759732751/1474284259',
        'Property': '/759732751/34094492',
        'RangeLayoutConstraint': '/759732751/1669293789',
        'RelativeLayoutConstraint': '/759732751/24011457',
        'RelativeRangeLayoutConstraint': '/759732751/1103499805',
        'Requirement': '/759732751/1220837843',
        'RequirementBase': '/759732751/1010911100',
        'RequirementCategory': '/759732751/1598195376',
        'RequirementsFolder': '/759732751/1675023230',
        'Result': '/759732751/1368062975',
        'Settings': '/759732751/319211427',
        'SimpleFormula': '/759732751/711037118',
        'Task': '/759732751/91705197',
        'Test': '/759732751/1922772359',
        'ValueFlowComposition': '/759732751/756182296',
        'WorkSpace': '/759732751/1826321976',
        'Workflow': '/759732751/891929219',
    };
});